add versioning step

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -62,6 +62,26 @@ workflows:
             
             flutter doctor -v
     - script:
+        title: Build - Set Environment Variables from Release Notes
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -e # fail build if any commands fails
+            #set -x # debug logging
+            
+            SEMANTIC_VERSION=`grep -o '[0-9]*\.[0-9]*\.[0-9]*' -m 1 release-notes.md`
+            envman add --key SEMANTIC_VERSION --value $SEMANTIC_VERSION
+            echo "Semantic Version:"
+            echo "v${SEMANTIC_VERSION}"
+            
+            RELEASE_NOTES=`pcre2grep -M '\*[\w\W]+\n\n' release-notes.md | sed '/^$/d'`
+            if [ -n RELEASE_NOTES ]; then
+                RELEASE_NOTES=`pcre2grep -M '\*[\w\W]+' release-notes.md`
+            fi
+            envman add --key RELEASE_NOTES --value ${RELEASE_NOTES}
+            echo "Release Notes:"
+            echo "${RELEASE_NOTES}"
+    - script:
         title: Build - Get Git Tags
         inputs:
         - content: |-
@@ -146,8 +166,6 @@ workflows:
         - destination: "$BITRISE_SOURCE_DIR/vsa.keystore"
     - script:
         title: Android - Substituting Keystore
-        run_if: |-
-                {{.IsCI | and (getenv "BUILD_ANDROID" | eq "1") | and (getenv "PRODUCTION" | eq "true")}}
         inputs:
         - content: |-
             #!/bin/bash
